.TH "wl_object" 3 "Fri Jun 12 2015" "Version 1.8.1" "Wayland" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wl_object \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wayland-server\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const struct \fBwl_interface\fP * \fBinterface\fP"
.br
.ti -1c
.RI "const void * \fBimplementation\fP"
.br
.ti -1c
.RI "uint32_t \fBid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Use of this header file is discouraged\&. Prefer including \fBwayland-server-core\&.h\fP instead, which does not include the client protocol header and as such only defines the library API, excluding the deprecated API below\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Wayland from the source code\&.
